package com.project.ministry_service.common.enums;

public enum RoleName {
    SENIOR_PASTOR,
    LEAD_PASTOR,
    ASSOCIATE_PASTOR,
    CHAIRMAN,
    PRESIDENT,
    SUPERINTENDENT,
    VICE_CHAIRMAN,
    VICE_PRESIDENT,
    COORDINATOR,
    ASSISTANT_COORDINATOR,
    DEACON,
    DEACONESS,
    SECRETARY,
    ASSISTANT_SECRETARY,
    TREASURER,
    ASSISTANT_TREASURER,
    FINANCE_OFFICER,
    ADVISOR,
    REPRESENTATIVE,
    IT_ADMINISTRATOR,
    MEDIA_DIRECTOR,
    PROGRAM_DIRECTOR,
    PUBLIC_RELATIONS_OFFICER,
    TEACHER,
    USHER,
    GREETER,
    MAINTENANCE_WORKER,
    CUSTODIAN,
    GROUNDSKEEPER,
    BUS_DRIVER,
    MECHANIC,
    APPLICATION_DEVELOPER,
    ELECTRICAL_TECHNICIAN,
    DANCER,
    PROJECTIONIST,
    AUDIO_ENGINEER,
    VIDEO_OPERATOR,
    LIGHTING_TECHNICIAN,
    MEDIA_CONTENT_CREATOR,
    TECHNICAL_SUPPORT,
    EVENT_PLANNER,
    SECURITY_OFFICER,
    VOLUNTEER,
    INTERN,
    TRAINEE,
    MEMBER
}


/*INSERT INTO roles (id, name, category, priority, description) VALUES
(gen_random_uuid(), 'Senior Pastor', 'HEAD', 1, 'The overall spiritual leader and overseer of the church or organization.'),
(gen_random_uuid(), 'Lead Pastor', 'HEAD', 2, 'Leads the main pastoral team, responsible for preaching, vision, and direction.'),
(gen_random_uuid(), 'Associate Pastor', 'HEAD', 3, 'Assists the Lead Pastor with ministry duties and church oversight.'),
(gen_random_uuid(), 'Director', 'HEAD', 4, 'Oversees a major ministry department (e.g., Youth, Worship, Education).'),
(gen_random_uuid(), 'Chairman', 'HEAD', 5, 'Head of a church board or deacons, responsible for major administrative oversight.'),
(gen_random_uuid(), 'President', 'HEAD', 6, 'Leads a ministry group or organization under the church’s umbrella.'),
(gen_random_uuid(), 'Superintendent', 'HEAD', 7, 'Oversees educational or departmental programs such as Sunday School.'),

(gen_random_uuid(), 'Vice Chairman', 'COMMITTEE', 8, 'Assists the Chairman and acts on their behalf when absent.'),
(gen_random_uuid(), 'Vice President', 'COMMITTEE', 9, 'Supports the President and takes over responsibilities if needed.'),
(gen_random_uuid(), 'Coordinator', 'COMMITTEE', 10, 'Manages specific activities or projects within a ministry.'),
(gen_random_uuid(), 'Assistant Coordinator', 'COMMITTEE', 11, 'Supports the Coordinator in planning and execution.'),
(gen_random_uuid(), 'Deacon', 'COMMITTEE', 12, 'Provides spiritual and practical service to the church, often assisting in administration.'),
(gen_random_uuid(), 'Deaconess', 'COMMITTEE', 13, 'Female deacon; supports service, outreach, and care ministries.'),
(gen_random_uuid(), 'Executive Member', 'COMMITTEE', 14, 'Part of the executive committee that makes key ministry decisions.'),
(gen_random_uuid(), 'Secretary', 'COMMITTEE', 15, 'Handles documentation, communication, and meeting records.'),
(gen_random_uuid(), 'Assistant Secretary', 'COMMITTEE', 16, 'Supports the Secretary with administrative duties.'),
(gen_random_uuid(), 'Treasurer', 'COMMITTEE', 17, 'Manages finances, budgets, and offerings within a ministry.'),
(gen_random_uuid(), 'Assistant Treasurer', 'COMMITTEE', 18, 'Helps the Treasurer track and manage financial records.'),
(gen_random_uuid(), 'Finance Officer', 'COMMITTEE', 19, 'Oversees detailed financial operations, reporting, and compliance.'),
(gen_random_uuid(), 'Advisor', 'COMMITTEE', 20, 'Provides wisdom, mentorship, and spiritual or administrative guidance.'),
(gen_random_uuid(), 'Representative', 'COMMITTEE', 21, 'Acts as a liaison between different ministries or teams.'),
(gen_random_uuid(), 'Worship Leader', 'COMMITTEE', 22, 'Leads the congregation in worship through music and prayer.'),
(gen_random_uuid(), 'Media Director', 'COMMITTEE', 23, 'Oversees media, livestreams, and technical operations for services.'),
(gen_random_uuid(), 'IT Administrator', 'COMMITTEE', 24, 'Manages software systems, technical setups, and digital infrastructure.'),
(gen_random_uuid(), 'Program Director', 'COMMITTEE', 25, 'Organizes events, programs, and church-wide initiatives.'),
(gen_random_uuid(), 'Public Relations Officer', 'COMMITTEE', 26, 'Handles public communication, announcements, and external relations.'),

(gen_random_uuid(), 'Teacher', 'REGULAR', 27, 'Instructs classes or Bible studies, particularly in educational ministries.'),
(gen_random_uuid(), 'Usher', 'REGULAR', 28, 'Welcomes attendees, assists with seating, and maintains order during services.'),
(gen_random_uuid(), 'Greeter', 'REGULAR', 29, 'Provides a warm welcome at the entrance, ensuring visitors feel at home.'),
(gen_random_uuid(), 'Maintenance Worker', 'REGULAR', 30, 'Handles upkeep and repairs around church facilities.'),
(gen_random_uuid(), 'Custodian', 'REGULAR', 31, 'Keeps church areas clean and organized.'),
(gen_random_uuid(), 'Groundskeeper', 'REGULAR', 32, 'Maintains outdoor spaces, gardens, and church property grounds.'),
(gen_random_uuid(), 'Bus Driver', 'REGULAR', 33, 'Operates transportation for members to and from church events.'),
(gen_random_uuid(), 'Driver', 'REGULAR', 34, 'Provides general transportation for church needs or staff.'),
(gen_random_uuid(), 'Mechanic', 'REGULAR', 35, 'Maintains and repairs church vehicles and machinery.'),
(gen_random_uuid(), 'Application Developer', 'REGULAR', 36, 'Builds and maintains software tools for ministry operations.'),
(gen_random_uuid(), 'Electrical Technician', 'REGULAR', 37, 'Installs and maintains lighting, sound, and power systems.'),
(gen_random_uuid(), 'Worship Team Member', 'REGULAR', 38, 'Performs as part of the worship team (vocals or instruments).'),
(gen_random_uuid(), 'Dancer', 'REGULAR', 39, 'Performs worship dances or artistic movements in services.'),
(gen_random_uuid(), 'Choir Member', 'REGULAR', 40, 'Sings in the choir or music group during services.'),
(gen_random_uuid(), 'Projectionist', 'REGULAR', 41, 'Manages lyric, scripture, and presentation projections during services.'),
(gen_random_uuid(), 'Audio Engineer', 'REGULAR', 42, 'Operates and maintains the sound system.'),
(gen_random_uuid(), 'Video Operator', 'REGULAR', 43, 'Handles video recording and live streaming.'),
(gen_random_uuid(), 'Lighting Technician', 'REGULAR', 44, 'Manages stage and ambient lighting during events.'),
(gen_random_uuid(), 'Media Content Creator', 'REGULAR', 45, 'Produces digital content such as graphics, videos, and posts.'),
(gen_random_uuid(), 'Technical Support', 'REGULAR', 46, 'Provides assistance for equipment or software used in ministry.'),
(gen_random_uuid(), 'Event Planner', 'REGULAR', 47, 'Coordinates events, schedules, and logistics for ministry activities.'),
(gen_random_uuid(), 'Hospitality Team Member', 'REGULAR', 48, 'Welcomes guests, manages receptions, and serves during gatherings.'),
(gen_random_uuid(), 'Security Officer', 'REGULAR', 49, 'Ensures safety of members, assets, and facilities during events.'),
(gen_random_uuid(), 'Volunteer', 'REGULAR', 50, 'Assists in various ministry activities as needed.'),
(gen_random_uuid(), 'Intern', 'REGULAR', 51, 'Gains ministry experience under supervision in a temporary position.'),
(gen_random_uuid(), 'Trainee', 'REGULAR', 52, 'Learns ministry or technical responsibilities under mentorship.');
*/